---
title: "Density_Models"
author: "Tessa Rehill"
date: "2024-12-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#read libraries 
```{r}
library(lme4)
library(corrplot)
library(glmmTMB)
library(DHARMa)

```

#Read in data 
```{r}
transects <- read.csv("/Users/tessarehill/Dropbox/MSc/Exclosures/processed_data/cleaned_monitoring_transects.csv")

plots <- read.csv("/Users/tessarehill/Dropbox/MSc/Exclosures/processed_data/cleaned_green_gravel_monitoring.csv")

env <- read.csv("/Users/tessarehill/Dropbox/MSc/Exclosures/processed_data/cleaned_ysi_measurement.csv")

hobo <- read.csv("/Users/tessarehill/Dropbox/MSc/Exclosures/processed_data/ENV/HOBO/summary_hobo.csv")

mean_depth_summary <- read.csv("/Users/tessarehill/Dropbox/MSc/Exclosures/processed_data/density_urchin_transects.csv")
```

#Formatting 
```{r}


#create env summary, for bottom temperature, do, ph, salinity
bottom_data <- env %>%
 group_by(site, month) %>%
  summarize(
    bottom_temp = temp[which.max(depth_m)],
    bottom_do = do[which.max(depth_m)],
    bottom_salinity = salinity[which.max(depth_m)],
    bottom_ph = ph[which.max(depth_m)],
    .groups = "drop" # Ungroups after summarization
  )

#make month a character
bottom_data <- bottom_data %>%
  mutate(month = as.character(month))

summary(bottom_data)

#merge environmental data and depth data by site/month to plot data 
plots_glm <- plots %>%
  left_join(hobo, by = c("site", "month")) %>%
  left_join(mean_depth_summary, by = c("site")) %>%
  left_join(bottom_data, by = c("site", "month"))


#log transform urchin density data (need to add a small constant because of zero values)
plots_glm$log_urchin_density <- log(plots_glm$urchin_density + 1)

#inspecting urchin distributions (to verify assumptions of fitting a GLMM)
hist(plots_glm$log_urchin_density, main = "Histogram of (log) Urchin Density", xlab = "Urchin Density")

#shapiro-Wilk test for normality, p less than 0.05, normally distributed
shapiro.test(plots_glm$log_urchin_density) #normally distributed 

mean_density <- mean(plots_glm$log_urchin_density, na.rm = TRUE)
var_density <- var(plots_glm$log_urchin_density, na.rm = TRUE)
overdispersion <- var_density / mean_density #0.653 (oof)
print(overdispersion) 
#check for over zero inflation 
sum(plots_glm$log_urchin_density == 0, na.rm = TRUE) / nrow(plots) #a lot of zeros (40%), use Zero-Inflated Guassian

plots_glm$month <- as.factor(plots_glm$month)
plots_glm$month <- as.numeric(plots_glm$month)
#correlation matrix of environmental variables 
cor_matrix <- cor(plots_glm[, c("mean_light_lux", "mean_temperature_c", 'bottom_salinity', 'bottom_ph', 'mean_depth_m', 'bottom_temp', 'bottom_do', 'month')], use = "complete.obs")
print(cor_matrix)

#visualize with a heatmap 
corrplot(cor_matrix, method = "circle")

#VIF factor - VIF quantifies how much the variance of a predictor is inflated due to multicollinearity. 
  #High VIF values (>5 or 10) indicate problematic collinearity. 
lm_model <- lm(log_urchin_density ~ bottom_temp + bottom_do + bottom_ph + bottom_salinity + mean_temperature_c + mean_light_lux, data = plots_glm) 

vif(lm_model) 

lm_model <- lm(log_urchin_density ~   mean_temperature_c + mean_light_lux, data = plots_glm)

vif(lm_model) #only HOBO measurements

lm_model <- lm(log_urchin_density ~   mean_temperature_c + mean_light_lux + bottom_do,  data = plots_glm)

vif(lm_model) 

lm_model <- lm(log_urchin_density ~   mean_temperature_c + mean_light_lux + bottom_do + bottom_salinity,  data = plots_glm)

vif(lm_model) #salinity = 5.75

lm_model <- lm(log_urchin_density ~   mean_temperature_c + mean_light_lux + bottom_do + month,  data = plots_glm)

vif(lm_model) 

#check for NA 
selected_plots <- plots_glm %>%
  dplyr::select(log_urchin_density, site, mean_temperature_c, treatment, month, mean_light_lux, bottom_do)

summary(selected_plots) #No NA values

#model! 
#standardizing predictors
plots_glm$mean_temperature_c <- scale(plots_glm$mean_temperature_c)
plots_glm$bottom_do <- scale(plots_glm$bottom_do)
plots_glm$mean_light_lux <- scale(plots_glm$mean_light_lux)
plots_glm$mean_depth_m <- scale(plots_glm$mean_depth_m)
plots_glm$month <- scale(plots_glm$month)


```


#Generalized Linear Model - Zero Inflation - Poisson 
```{r}
#include ALL predictors in first model 
model1 <- glmmTMB(log_urchin_density ~ mean_depth_m, mean_light_lux + mean_temperature_c + bottom_do + month +
                  (1 | site) + (1 | month) ,
                  zi = ~ treatment + mean_temperature_c + site_density + gravel_size + 
                        mean_light_lux + urchin_density + bottom_do + month,
                  family = nbinom2, 
                  data = model_df)
summary(model1)
AIC(model1) #943
```




#Zero Inflated Negative Binomial GLMM 

#Visualize 
```{r}
library(DHARMa)

fittedModel <- model_gau_1

testDispersion(fittedModel) #check for overdispersion

simulationOutput <- simulateResiduals(fittedModel = fittedModel, plot = T)
simulationOutput
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
