---
title: "GLM"
author: "Tessa Rehill"
date: "2025-02-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#load packages 

```{r}
library(here)
library(dplyr)
library(ggplot2)
library(ggcorrplot)
library(corrplot)
library(car)
library(glmmTMB)
library(DHARMa)
library(caret)
library(GGally)
library(broom.mixed)
library(dotwhisker)
library(ggplot2)
library(broom)
library(lme4)
library(lmerTest)

```

#load data
```{r}
data <- read.csv("/Users/tessarehill/Dropbox/MSc/Exclosures/processed_data/cleaned_data.csv")
```

#GLMM - urchins
#we use glmTMB because our data is overdispersed 
```{r}

data$urchin_density_cor <- data$urchin_density + 0.001


density_model <- glmmTMB(urchin_density_cor ~ treatment  + site, 
                      family = Gamma(link = "log"), 
                      data = data)

summary(density_model)


#visualize model 
fittedModel <- density_model

simulationOutput <- simulateResiduals(fittedModel = fittedModel, plot = T)
simulationOutput

#how does this compare to a tweedie distribution, tweedie distribution is BETTER 
density_model <- glmmTMB(urchin_density ~ treatment  + site + month, 
                      family = tweedie(link = "log"), 
                      data = data)

summary(density_model)


#visualize model 
fittedModel <- density_model

simulationOutput <- simulateResiduals(fittedModel = fittedModel, plot = T)
simulationOutput

```

#GLM - KELP 
```{r}

survival_model <- glmmTMB(cbind(n_kelp_gravel, n_gravel - n_kelp_gravel) ~ treatment  + site + gravel_size, 
                      family = binomial, 
                      data = data)

summary(survival_model)

#visualize model 
fittedModel <- survival_model

simulationOutput <- simulateResiduals(fittedModel = fittedModel, plot = T)
simulationOutput


growth_model <- glmmTMB(kelp_growth ~ treatment + gravel_size + site , 
                      family = tweedie(link = "log"), 
                      data = data)

summary(growth_model)

#visualize model 
fittedModel <- growth_model

simulationOutput <- simulateResiduals(fittedModel = fittedModel, plot = T)
simulationOutput
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
