---
title: "Kelp_GLMM"
author: "Tessa Rehill"
date: "2025-03-11"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
```

#Load libraries 

```{r}
library(here)
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggcorrplot)
library(corrplot)
library(car)
library(glmmTMB)
library(DHARMa)
library(caret)
library(GGally)
library(broom.mixed)
library(dotwhisker)
library(broom)
library(lme4)
library(lmerTest)
library(visreg)   # model fit visualizations
library(emmeans)  # estimate effects
library(car)      # linear model utilities
library(nlme)     # lme() in nlme package
library(MASS)     # confidence intervals
library(MuMIn)    # model selection
```

#Load data 
```{r}
data <- read.csv("/Users/tessarehill/Dropbox/MSc/Exclosures/processed_data/cleaned_data.csv")

#remove growth = 0 from dataset 
growth_data <- data %>% drop_na(kelp_growth)


scaled_data <-  data %>%
  mutate(across(c(urchin_site_density, urchin_density, ts_density, ts_site_density, 
                  mean_temperature_c, max_temperature_c, mean_light_lux, 
                  mean_current, max_current, bottom_salinity, bottom_do, bottom_ph), 
                scale)) %>%
  na.omit(data)


scaled_growth_data <-  growth_data %>%
  mutate(across(c(urchin_site_density, urchin_density, ts_density, ts_site_density, 
                  mean_temperature_c, max_temperature_c, mean_light_lux, 
                  mean_current, bottom_salinity, max_current, bottom_do, bottom_ph), 
                scale))%>%
  na.omit(scaled_growth_data)


```

#Correlation among ABIOTIC predictors
```{r}
cor_matrix <- cor(data[, c("mean_light_lux", "mean_temperature_c", "max_temperature_c",  "mean_current", "bottom_salinity",  "bottom_do", "bottom_ph" )], use = "complete.obs")

#rename variables
# Rename row and column names
colnames(cor_matrix) <- rownames(cor_matrix) <- c("Light (lux)", "Temp (mean)", "Temp (max)", 
                                                  "Current (mean)", "Bottom salinity", "Bottom DO", 
                                                  "Bottom pH")

#create the correlation plot
plot <- ggcorrplot(
  cor_matrix, 
  method = "circle",   #use circles for visualization
  lab = TRUE           #add correlation coefficients as labels
)
plot

#save the plot
ggsave("/Users/tessarehill/Dropbox/MSc/Exclosures/plots/models/abiotic_correlation_plot.png", plot = plot, width = 10, height = 8, dpi = 300)

```

#KELP SURVIVAL w/ DREDGING 
```{r}
global_model <- glmmTMB(cbind(n_kelp_gravel, n_gravel - n_kelp_gravel) ~ treatment  + urchin_site_density + urchin_density + ts_site_density + ts_density +  gravel_size  + mean_temperature_c + max_temperature_c +  mean_light_lux + mean_current + bottom_do + bottom_salinity + (1 | site), 
                      family = binomial(link="logit"), 
                      data = scaled_data, 
                      na.action = "na.fail")  # Ensure missing data handling is explicit)

summary(global_model)


b <- dredge(global_model, beta = c("none", "sd", "partial.sd"), evaluate = TRUE,
  rank = "AICc", fixed = "cond(treatment)")


get.models(b, subset = 1)[[1]] 


```

#Summarize best model results 
```{r}
best_model <- glmmTMB(cbind(n_kelp_gravel, n_gravel - n_kelp_gravel) ~ treatment + gravel_size + max_temperature_c + ts_site_density + max_temperature_c  +bottom_do + (1 | site), 
                      family = binomial, 
                      data = data)  #

summary(best_model)

best_growth_model <- glmmTMB(kelp_growth ~ treatment  +  urchin_site_density + ts_site_density + (1 | site), 
                      family = Gamma(link="log"), 
                      data = data)

summary(best_growth_model)


```

#VIF - check colinearity 
```{r}
lm_model <- lm(n_gravel ~ treatment + gravel_size +  mean_light_lux + max_temperature_c + urchin_site_density + bottom_do, data = data)

vif(lm_model, type="predictor") 
```


#Visualize model result
```{r}
#final model
fittedModel <- best_model

testDispersion(fittedModel) #check for overdispersion

simulationOutput <- simulateResiduals(fittedModel = fittedModel, plot = T)
simulationOutput

#save the testDispersion plot
png("/Users/tessarehill/Dropbox/MSc/Exclosures/plots/models/beta_testDispersion_plot.png", width = 800, height = 600)
testDispersion(fittedModel)
dev.off()

#save the QQ plot
png("/Users/tessarehill/Dropbox/MSc/Exclosures/plots/models/beta_QQ_plot.png", width = 800, height = 600)
plotQQunif(simulationOutput)  # Generate QQ plot
dev.off()

#save residual vs predictor plot
png("/Users/tessarehill/Dropbox/MSc/Exclosures/plots/models/beta_residuals_vs_predictor.png", width = 800, height = 600)
plotResiduals(simulationOutput)
dev.off()

```









#Kelp survival GLMM - Dredging 
```{r}


global_model <- glmmTMB(cbind(n_kelp_gravel, n_gravel - n_kelp_gravel) ~ treatment  +  urchin_site_density + urchin_density + ts_density + ts_site_density + gravel_size + mean_temperature_c + max_temperature_c + mean_light_lux + mean_current + bottom_salinity + bottom_do  + (1 | site), 
                      family = binomial(link="logit"), 
                      data = scaled_data, 
                      na.action = "na.fail")  # Ensure missing data handling is explicit)

summary(global_model)


a <- dredge(global_model, beta = c("none", "sd", "partial.sd"), evaluate = TRUE,
  rank = "AICc", fixed = NULL)

get.models(a, subset = 1)[[1]] 



best_model_no_NA <- glmmTMB(cbind(n_kelp_gravel, n_gravel - n_kelp_gravel) ~ treatment  + ts_site_density + gravel_size + max_temperature_c +bottom_do  + (1 | site), 
                      family = binomial(link="logit"), 
                      data = scaled_data)

best_model_all_data <- glmmTMB(cbind(n_kelp_gravel, n_gravel - n_kelp_gravel) ~ treatment  + ts_site_density + gravel_size + max_temperature_c +bottom_do  + (1 | site), 
                      family = binomial(link="logit"), 
                      data = data)



```



```{r}
global_model <- glmmTMB(cbind(n_kelp_gravel, n_gravel - n_kelp_gravel) ~ treatment  +  urchin_site_density + urchin_density + ts_site_density + ts_density + gravel_size + mean_temperature_c + max_temperature_c + mean_light_lux + mean_current + bottom_salinity + bottom_do  + (1 | site), 
                      family = binomial(link="logit"), 
                      data = scaled_data, 
                      na.action = "na.fail")  # Ensure missing data handling is explicit)

summary(global_model)


a <- dredge(global_model, beta = c("none", "sd", "partial.sd"), evaluate = TRUE,
  rank = "AIC", fixed = NULL)

get.models(a, subset = 1)[[1]] 


modela <- glmmTMB(cbind(n_kelp_gravel, n_gravel - n_kelp_gravel) ~ treatment  + bottom_do + bottom_ph + gravel_size + ts_site_density + (1 | site), 
                      family = binomial(link="logit"), 
                      data = data)


summary(modela)
```

#Kelp Growth 
```{r}
scaled_growth_data <-  growth_data %>%
  mutate(across(c(urchin_site_density, urchin_density, ts_density, ts_site_density, 
                  mean_temperature_c, max_temperature_c, mean_light_lux, 
                  mean_current, bottom_salinity, bottom_do, bottom_ph), 
                scale))%>%
  na.omit(scaled_growth_data)


scaled_growth_data <- na.omit(scaled_growth_data)


global_model <- glmmTMB(kelp_growth ~ treatment  +  urchin_site_density + urchin_density + ts_density + ts_site_density + gravel_size + mean_temperature_c + max_temperature_c + mean_light_lux + mean_current + bottom_salinity + bottom_do  + (1 | site), 
                      family = Gamma(link="log"), 
                      data = scaled_growth_data, 
                      na.action = "na.fail")  # Ensure missing data handling is explicit)

summary(global_model)


z <- dredge(global_model, beta = c("none", "sd", "partial.sd"), evaluate = TRUE,
  rank = "AICc", fixed = NULL)

get.models(z, subset = 1)[[1]] 




global_model <- glmmTMB(kelp_growth ~ treatment  +  urchin_site_density + ts_site_density + gravel_size  + max_temperature_c +  mean_light_lux + mean_current + bottom_do + mean_temperature_c + (1 | site), 
                      family = Gamma(link="log"), 
                      data = scaled_growth_data, 
                      na.action = "na.fail")  # Ensure missing data handling is explicit)

b <- dredge(global_model, beta = c("none", "sd", "partial.sd"), evaluate = TRUE,
  rank = "AICc", fixed = "cond(treatment)")

get.models(b, subset = 1)[[1]] 


```


```{r}
global_model <- glmmTMB(kelp_growth ~ treatment  +  urchin_site_density + urchin_density +  gravel_size + mean_temperature_c + max_temperature_c + mean_light_lux + mean_current + bottom_salinity + bottom_do   + (1 | site), 
                      family = Gamma(link="log"), 
                      data = scaled_growth_data, 
                      na.action = "na.fail")  # Ensure missing data handling is explicit)

summary(global_model)


d <- dredge(global_model, beta = c("none", "sd", "partial.sd"), evaluate = TRUE,
  rank = "AIC", fixed = treatment)

get.models(d, subset = 1)[[1]] 

model1 <- glmmTMB(kelp_growth ~ mean_light_lux + urchin_density + urchin_site_density  + (1 | site), 
                      family = Gamma(link="log"),
                      data = data)

summary(model1)
```
```{r}
global_model <- glmmTMB(kelp_growth ~ treatment  +  grazers_site_density + grazer_density +  gravel_size + mean_temperature_c + max_temperature_c + mean_light_lux + mean_current + bottom_salinity + bottom_do   + (1 | site), 
                      family = Gamma(link="log"), 
                      data = scaled_growth_data, 
                      na.action = "na.fail")  # Ensure missing data handling is explicit)

summary(global_model)


e <- dredge(global_model, beta = c("none", "sd", "partial.sd"), evaluate = TRUE,
  rank = "AIC", fixed = NULL)

get.models(e, subset = 1)[[1]] 

model1 <- glmmTMB(kelp_growth ~ mean_light_lux + urchin_density + urchin_site_density  + (1 | site), 
                      family = Gamma(link="log"),
                      data = data)

summary(model1)
```
```{r}
global_model <- glmmTMB(cbind(n_kelp_gravel, n_gravel - n_kelp_gravel) ~ treatment  +  grazers_site_density + grazer_density +  gravel_size + mean_temperature_c + max_temperature_c + mean_light_lux + mean_current + bottom_salinity + bottom_do  + (1 | site), 
                      family = binomial(link="logit"), 
                      data = scaled_data, 
                      na.action = "na.fail")  # Ensure missing data handling is explicit)

summary(global_model)



f <- dredge(global_model, beta = c("none", "sd", "partial.sd"), evaluate = TRUE,
  rank = "AIC", fixed = NULL)

get.models(f, subset = 1)[[1]] 
```
```{r}
global_model <- glmmTMB(kelp_growth ~ treatment  +  urchin_site_density + urchin_density +  gravel_size + mean_temperature_c + max_temperature_c + mean_light_lux + mean_current + bottom_salinity + bottom_do   + (1 | site), 
                      family = Gamma(link="log"), 
                      data = scaled_growth_data, 
                      na.action = "na.fail")  # Ensure missing data handling is explicit)

summary(global_model)


k <- dredge(global_model, beta = c("none", "sd", "partial.sd"), evaluate = TRUE,
  rank = "AIC", fixed = c('treatment')) #can't do fixed treatment with glmmTMB

get.models(k, subset = 1)[[1]] 
```
```{r}

global_model <- glmer(kelp_growth ~ treatment  +  urchin_site_density + urchin_density +  gravel_size  + max_temperature_c + mean_light_lux + mean_current + bottom_salinity + bottom_do   + (1 | site), 
                      family = Gamma(link="log"), 
                      data = scaled_growth_data, 
                      na.action = "na.fail")  # Ensure missing data handling is explicit)

summary(global_model)


k <- dredge(global_model, beta = c("none", "sd", "partial.sd"), evaluate = TRUE,
  rank = "AIC", fixed = c('treatment')) #can't do fixed treatment with glmmTMB

get.models(k, subset = 1)[[1]] 
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
